name: dartagnan
description: Just a Discord bot.
version: 1.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  nyxx: ^3.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  very_good_analysis: ^3.0.0
