name: dartagnan
description: Just a Discord bot.
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  nyxx: ^3.4.2

dev_dependencies:
  blackfoot_flutter_lint: ^1.1.0
  test: ^1.16.0
